const fs = require("fs");
const img = [
  "http://localhost:8000/assests/images/img1.jpeg",
  "http://localhost:8000/assests/images/img2.webp",
  "http://localhost:8000/assests/images/img3.jpeg",
  "http://localhost:8000/assests/images/img4.jpeg",
  "http://localhost:8000/assests/images/img5.jpeg",
  "http://localhost:8000/assests/images/img6.jpeg",
  "http://localhost:8000/assests/images/img7.jpeg",
  "http://localhost:8000/assests/images/img8.jpeg",
  "http://localhost:8000/assests/images/img9.webp",
  "http://localhost:8000/assests/images/img10.webp",
  "http://localhost:8000/assests/images/img11.jpeg",
  "http://localhost:8000/assests/images/img12.webp",
  "http://localhost:8000/assests/images/img13.webp",
  "http://localhost:8000/assests/images/img14.webp",
  "http://localhost:8000/assests/images/img15.jpeg",
  "http://localhost:8000/assests/images/img16.jpeg",
  "http://localhost:8000/assests/images/img17.jpeg",
  "http://localhost:8000/assests/images/img18.webp",
  "http://localhost:8000/assests/images/img19.jpeg",
  "http://localhost:8000/assests/images/img20.webp",
  "http://localhost:8000/assests/images/img21.jpeg",
  "http://localhost:8000/assests/images/img22.webp",
];
const descriptionText =
  "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge";

const data = [
  {
    id: 1,
    title: "Avant-garde Lamp",
    category: "Kids",
    cost: 179.99,
    img: img[0],
    madeBy: "Modenza",
    description: descriptionText,
    amount: 0,
    tax: 12,
    freeShipping : 0
  },
  {
    id: 2,
    title: "Chic Chair",
    category: "Chair",
    cost: 339.99,
    img: img[1],
    madeBy: "Luxora",
    description: descriptionText,
    amount: 0,
    tax: 18,
    freeShipping : 1
  },
  {
    id: 3,
    title: "Coffee Table",
    category: "Tables",
    cost: 179.99,
    img: img[2],
    madeBy: "Modenza",
    description: descriptionText,
    amount: 0,
    tax: 32,
    freeShipping : 0
  },
  {
    id: 4,
    title: "Comfy Bed",
    category: "Beds",
    cost: 129.99,
    img: img[3],
    madeBy: "Modenza",
    description: descriptionText,
    amount: 0,
    tax: 34,
    freeShipping : 0
  },
  {
    id: 5,
    title: "Contemporary Sofa",
    category: "Sofas",
    cost: 159.99,
    img: img[4],
    madeBy: "Comfora",
    description: descriptionText,
    amount: 0,
    tax: 50,
    freeShipping : 0
  },
  {
    id: 6,
    title: "Cutting-Edge Bed",
    category: "Beds",
    cost: 84.99,
    img: img[5],
    madeBy: "Homestead",
    description: descriptionText,
    amount: 0,
    tax: 40,
    freeShipping : 1
  },
  {
    id: 7,
    title: "Futuristic Shelves",
    category: "Kids",
    cost: 94.99,
    img: img[6],
    madeBy: "Luxora",
    description: descriptionText,
    amount: 0,
    tax: 20,
    freeShipping : 1
  },
  {
    id: 8,
    title: "Glass Table",
    category: "Tables",
    cost: 159.99,
    img: img[7],
    madeBy: "Modenza",
    description: descriptionText,
    amount: 0,
    tax: 23,
    freeShipping : 0
  },
  {
    id: 9,
    title: "King Bed",
    category: "Beds",
    cost: 189.99,
    img: img[8],
    madeBy: "Homestead",
    description: descriptionText,
    amount: 0,
    tax: 28,
    freeShipping : 1
  },
  {
    id: 10,
    title: "Lounge Chair",
    category: "Chair",
    cost: 259.99,
    img: img[9],
    madeBy: "Luxora",
    description: descriptionText,
    amount: 0,
    tax: 15,
    freeShipping : 0
  },
  {
    id: 11,
    title: "Mimimalist Shelves",
    category: "Kids",
    cost: 439.99,
    img: img[10],
    madeBy: "Artifex",
    description: descriptionText,
    amount: 0,
    tax: 16,
    freeShipping : 0
  },
  {
    id: 12,
    title: "Modern Sofa",
    category: "Sofas",
    cost: 299.99,
    img: img[11],
    madeBy: "Comfora",
    description: descriptionText,
    amount: 0,
    tax: 17,
    freeShipping : 0
  },
  {
    id: 13,
    title: "Modern Table",
    category: "Tables",
    cost: 389.99,
    img: img[12],
    madeBy: "Modenza",
    description: descriptionText,
    amount: 0,
    tax: 18,
    freeShipping : 1
  },
  {
    id: 14,
    title: "Reclining Sofa",
    category: "Sofas",
    cost: 329.99,
    img: img[13],
    madeBy: "Comfora",
    description: descriptionText,
    amount: 0,
    tax: 19,
    freeShipping : 0
  },
  {
    id: 15,
    title: "Sectional Sofa",
    category: "Sofas",
    cost: 359.99,
    img: img[14],
    madeBy: "Comfora",
    description: descriptionText,
    amount: 0,
    tax: 40,
    freeShipping : 1
  },
  {
    id: 16,
    title: "Sleek Bed",
    category: "Beds",
    cost: 539.99,
    img: img[15],
    madeBy: "Homestead",
    description: descriptionText,
    amount: 0,
    tax: 10,
    freeShipping : 1
  },
  {
    id: 17,
    title: "Sleek Chair",
    category: "Chair",
    cost: 199.99,
    img: img[16],
    madeBy: "Luxora",
    description: descriptionText,
    amount: 0,
    tax: 8,
    freeShipping : 0
  },
  {
    id: 18,
    title: "Streamlined Table",
    category: "Tables",
    cost: 209.99,
    img: img[17],
    madeBy: "Modenza",
    description: descriptionText,
    amount: 0,
    tax: 35,
    freeShipping : 1
  },
  {
    id: 19,
    title: "Stylish Bed",
    category: "Beds",
    cost: 169.99,
    img: img[18],
    madeBy: "Homestead",
    description: descriptionText,
    amount: 0,
    tax: 26,
    freeShipping : 1
  },
  {
    id: 20,
    title: "Toy Shelf",
    category: "Kids",
    cost: 79.99,
    img: img[19],
    madeBy: "Luxora",
    description: descriptionText,
    amount: 0,
    tax: 38,
    freeShipping : 0
  },
  {
    id: 21,
    title: "Velvet Sofa",
    category: "Sofas",
    cost: 289.99,
    img: img[20],
    madeBy: "Luxora",
    description: descriptionText,
    amount: 0,
    tax: 50,
    freeShipping : 1
  },
  {
    id: 22,
    title: "Wooden Shelves",
    category: "Kids",
    cost: 119.99,
    img: img[21],
    madeBy: "Artifex",
    description: descriptionText,
    amount: 0,
    tax: 33,
    freeShipping : 0
  },
];

module.exports = data;
